# Generated by Django 5.2.3 on 2026-05-31 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='rank_score',
            field=models.IntegerField(default=1500, verbose_name='Rank Score'),
        ),
    ]
