# Generated by Django 5.2.3 on 2026-05-31 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_userprofile_rank_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='current_rank_score',
            field=models.IntegerField(default=1500, verbose_name='当前天梯分'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='rank_score',
            field=models.IntegerField(default=1500, verbose_name='历史最高天梯分'),
        ),
    ]
